# Generated by Django 4.1.5 on 2023-01-20 19:42

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Teacher", "Teacher")],
                default="Student",
                max_length=30,
                validators=[account.models.role_validator],
            ),
        ),
    ]
