# Generated by Django 4.1.5 on 2023-02-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="relationship",
            field=models.ManyToManyField(
                blank=True, related_name="relationship_with", to="account.userprofile"
            ),
        ),
    ]
