# Generated by Django 4.1.5 on 2023-01-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="MusicUser",
        ),
    ]
