# Generated by Django 4.1.5 on 2023-01-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_message_sender_alter_message_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
