# Generated by Django 4.1.5 on 2023-01-18 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("Student", "Student"), ("Teacher", "Teacher")],
                default="Student",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "Student|Teacher",
                        code="invalid role",
                        message="Role must be Student or Teacher",
                    )
                ],
            ),
        ),
    ]
