# Generated by Django 4.1.5 on 2023-01-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_message_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
